### ISSUE TITLE
Rings are off-center

### ISSUE THREAD

**Issue by keem85** [mbucchia/_ARCHIVE_XR_APILAYER_NOVENDOR_nis_scaler#28]
Hello. I've noticed that the rings on the HP Reverb G2 are off center.. If I shrink the outer ring to say 20% and 1/16, I see the bad outer ring graphics on the left eye only, right eye is almost clean.. Seems that the center is a bit off?

RTX 3090
12900K

**Comment by mbucchia-msft** [comment]
Are you using 100% render scale in the game?

**Comment by keem85** [comment]
> Are you using 100% render scale in the game?

Hey! I'm using 220% OpenXR scaling, and 65% ingame render scale. I found that to be the best performance ratio for me

**Comment by mbucchia-msft** [comment]
unfortunately in-game render scale not set at 100% is not supported with our implementation of FFR.

**Comment by keem85** [comment]
Okay, setting it to 100% fixed the off center vertically, but now I see more outer ring on the bottom and clean on top. It's at least better now, not perfectly centered, but better

**Comment by mbucchia-msft** [comment]
You can use the Expert settings (in the Menu tab) to enable more options to adjust for you. One setting is called Vertical offset and can help you adjust to fix what you said.
