### ISSUE TITLE
Bonelab Crashes on XR loading

### ISSUE THREAD

**Issue by Josh249** [mbucchia/_ARCHIVE_XR_APILAYER_NOVENDOR_nis_scaler#29]
When using this software, Bonelab crashes. Log file tells you what happened.
[XR_APILAYER_NOVENDOR_nis_scaler.log](https://github.com/mbucchia/_ARCHIVE_XR_APILAYER_NOVENDOR_nis_scaler/files/9741298/XR_APILAYER_NOVENDOR_nis_scaler.log)

Is it because I need to download it in the drive that has the game?

**Comment by mbucchia** [comment]
NIS scaler is no longer maintained. 

Use https://mbucchia.github.io/OpenXR-Toolkit/ instead. It works great with Bonelab.
