### ISSUE TITLE
Morrowind VR with nis scaler (OpenMW)

### ISSUE THREAD

**Issue by BrziJoe** [mbucchia/_ARCHIVE_XR_APILAYER_NOVENDOR_nis_scaler#3]
Hi, I am happy that you made this tool. As I do not have MSFS2020, I tried it in another openxr game; Morrovind VR. I got right name of config file (openmw_vr.cfg), and generally it is working.

However, the shortcuts (Ctrl + left/or F1) do not show any change. I tried really low scale (0.5), and that is visible in game, but I expect some change in quality when pressing ctrl+left (or ctrl+F1), but in my case there is no change at all.
Are you sure shortcut for NIS/biliner swap works?

Similar, I was expecting bigger change with sharpening 0.00 vs 1.00, but it is barely visible. (ctrl+up/down/F2/F3 pushing many, many times makes no visual changes) I have already a lot of experience with NIS in other Steamvr games, so I know what to expect, sort of..
Log shows changes in sharpness:
[XR_APILAYER_NOVENDOR_nis_scaler.log](https://github.com/mbucchia/XR_APILAYER_NOVENDOR_nis_scaler/files/7710436/XR_APILAYER_NOVENDOR_nis_scaler.log)

**Comment by mbucchia-msft** [comment]
Thanks for the feedback!

According to your log, the scaling software did not activate for this game since it requires 2 features that I actually don't support yet. I am prioritizing MSFS2020 support at the moment, but these 2 features are on my list for later.

Thanks for pointing out this game. The log also tells me what specific texture format I need to add support for, which is very helpful. So when I have some more time, I will try to get them to work.

Thanks for your patience!

**Comment by mbucchia** [comment]
@BrziJoe is there a free demo of this game somewhere? I understand that the VR mod is free, but you still need the original game?

**Comment by mbucchia** [comment]
This looks promising for my needs: https://forum.openmw.org/viewtopic.php?t=3595

**Comment by BrziJoe** [comment]
([hi, please activate it asap, it is easier this way :)](https://mega.nz/file/FIE12SLB#Mwb8S0rIDUWJ4Y3yunKxBifpV5sXWOM5fXxmbujcf-g))

**Comment by mbucchia** [comment]
Sorry but I am going to ask you to remove this immediately. I will not claim this key and as a software professional,  I will not take part in piracy.

**Comment by BrziJoe** [comment]
Sorry, that is a good point. I was using it as a regular store with keys from steam sale. But if you say so, you sure know better.

**Comment by mbucchia** [comment]
Don't worry I'll find another way to try out this case!

**Comment by BrziJoe** [comment]
Is it ok if I send you now key directly from steam? That is the least what I can do

**Comment by mbucchia** [comment]
Let me try the example suite thing first. I have high hopes (it's literally meant for developers to test)

**Comment by mbucchia** [comment]
Can you give it a try with the new project: https://mbucchia.github.io/OpenXR-Toolkit/

I'm pretty sure it will go further, but don't know if it will work for real. Please send me logs after!

Thanks.

**Comment by BrziJoe** [comment]
hi, just tried it. I really can not tell is it working; every scale looks just blurry, just like last time. I wish I can turn FSR off/on live, but here I just got message that I probably need to restart. Logs are here, and one screenshot from dds - It does not show proper picture, just maybe some layer, please take a look:
[logs.zip](https://github.com/mbucchia/XR_APILAYER_NOVENDOR_nis_scaler/files/7970542/logs.zip)


And I use Pimax with canted displays; the virtual box in front of me can not be aligned properly with left-right correction. The problem is that this box is perpendicular to eyes, and it should be perpendicular to head. 
![Sketch](https://user-images.githubusercontent.com/35833650/151793419-ea61b9c5-3748-4daf-9f66-f0c3ed394a3a.jpg)


PS: one more note, I use Fholgers FSR tool a lot in steamvr games, well in every game. Some games are too demanding, then I set scale to less than 1, same as here. But some other games are not demanding at all, then I can set scale there to bigger then 1; his tool make it then different than yours - it renders then native resolution (i.E. always 100% steam ss, for me 3160 pixels vertical), and adds FSR supersampling to biger resolution. 
With his approach I can have always same steamvr settings, and can just change FSR scale per game.
I know that this is your tool, and that I might ask too much now, but with his approach is much easier to fine tune many, many games. 
Anyway, it is up to you, any I can manage my games either way. Do not think much about this ;)

**Comment by BrziJoe** [comment]
I play more with different settings, resolutions, and scenes in game. I admit that your tool works in Morrowind, at least sharpening is visible, and it is easier to see in really high resolutions.

Probably this game mod (pretty light weit on resources, and with simple textures) is not the best example for checking NIS/FSR. Also mod is sure high cpu bounded, as my vr fps were pretty much with any settings between 50-70.  Lower resolution give same fps as higher, strange.

The game mod have at least 2 layers: actual game + vr hands or menu box. The hands and menu is crazy sharp and clear all the time. 

The screenshots (.dds) are defective. You can see example above in attach. 
What does it mean? Are all layers working with your tool?

**Comment by mbucchia** [comment]
> hi, just tried it. I really can not tell is it working; every scale looks just blurry, just like last time. I wish I can turn FSR off/on live, but here I just got message that I probably need to restart. Logs are here, 

If you can access the menu on-screen, then it works. Looking at your captured log file, it also seems to confirm that the toolkit is working.

You can turn off/on live for quick testing by using an undocumented feature:
1) Enable NIS or FSR
2) Restart for the changes to take effect
3) Open the menu, and set Upscaling to Off

This will temporarily disable the upscaling filter (same as what Ctrl+F1 did in the NIS scaler).

> and one screenshot from dds - It does not show proper picture, just maybe some layer, please take a look:

Can you try using GIMP to open the image? Many apps don't work well with DDS files. I don't know about XnView.

> And I use Pimax with canted displays; the virtual box in front of me can not be aligned properly with left-right correction.

This is a known issue, we will try to do something about it but we don't have Pimax hardware to test with.

> I play more with different settings, resolutions, and scenes in game. I admit that your tool works in Morrowind, at least sharpening is visible, and it is easier to see in really high resolutions.

Thanks for following up with more results!

> Also mod is sure high cpu bounded, as my vr fps were pretty much with any settings between 50-70.

You can use the Detailed overlay to investigate that: https://mbucchia.github.io/OpenXR-Toolkit/overlay.html

It will help you tell if you are indeed CPU bound.

**Comment by BrziJoe** [comment]
![Morrv2](https://user-images.githubusercontent.com/35833650/151977917-211d968e-1911-4a9f-b177-743fff13085b.png)
